In [7]:
# Import libraries
import numpy as np 
import pandas as pd
import category_encoders as ce

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score 

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [8]:
# Load the dataset
df = pd.read_csv("Downloads\life\life.csv")

In [9]:
df

          Country  Year      Status  ...   thinness 5-9 years  Income composition of resources  Schooling
0     Afghanistan  2015  Developing  ...                 17.3                            0.479       10.1
1     Afghanistan  2014  Developing  ...                 17.5                            0.476       10.0
2     Afghanistan  2013  Developing  ...                 17.7                            0.470        9.9
3     Afghanistan  2012  Developing  ...                 18.0                            0.463        9.8
4     Afghanistan  2011  Developing  ...                 18.2                            0.454        9.5
...           ...   ...         ...  ...                  ...                              ...        ...
2933     Zimbabwe  2004  Developing  ...                  9.4                            0.407        9.2
2934     Zimbabwe  2003  Developing  ...                  9.9                            0.418        9.5
2935     Zimbabwe  2002  Developing  ...                  1.3                            0.427       10.0
2936     Zimbabwe  2001  Developing  ...                  1.7                            0.427        9.8
2937     Zimbabwe  2000  Developing  ...                 11.2                            0.434        9.8

[2938 rows x 22 columns]

In [10]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [11]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [12]:
df.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

In [13]:
df.Status.value_counts()

Status
Developing    2426
Developed      512
Name: count, dtype: int64

In [14]:
# Encoding Status
a = pd.get_dummies(df.Status).astype(int) 
a = a.drop("Developed", axis = 1)
df = pd.concat([a,df],axis = 1)

In [15]:
df = df.drop("Status", axis = 1)
df.rename(columns = {"Developing":"Status"},inplace = True)

In [16]:
df

      Status      Country  Year  ...   thinness 5-9 years  Income composition of resources  Schooling
0          1  Afghanistan  2015  ...                 17.3                            0.479       10.1
1          1  Afghanistan  2014  ...                 17.5                            0.476       10.0
2          1  Afghanistan  2013  ...                 17.7                            0.470        9.9
3          1  Afghanistan  2012  ...                 18.0                            0.463        9.8
4          1  Afghanistan  2011  ...                 18.2                            0.454        9.5
...      ...          ...   ...  ...                  ...                              ...        ...
2933       1     Zimbabwe  2004  ...                  9.4                            0.407        9.2
2934       1     Zimbabwe  2003  ...                  9.9                            0.418        9.5
2935       1     Zimbabwe  2002  ...                  1.3                            0.427       10.0
2936       1     Zimbabwe  2001  ...                  1.7                            0.427        9.8
2937       1     Zimbabwe  2000  ...                 11.2                            0.434        9.8

[2938 rows x 22 columns]

In [18]:
X = df.drop('Life expectancy ', axis=1)
y = df['Life expectancy ']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
encoder = ce.TargetEncoder(cols=['Country'], smoothing=10)

X_train['Country_Encoded'] = encoder.fit_transform(X_train[['Country']],y_train)
X_test['Country_Encoded'] = encoder.transform(X_test[['Country']])
X_train = X_train.drop('Country', axis=1)
X_test = X_test.drop('Country', axis=1)

In [23]:
X_train

      Status  Year  Adult Mortality  ...  Income composition of resources  Schooling  Country_Encoded
456        1  2007            126.0  ...                            0.602       11.9        70.389873
462        1  2001            152.0  ...                            0.562       11.0        70.389873
2172       1  2011            143.0  ...                            0.733       12.9        70.872090
2667       1  2013             13.0  ...                            0.720       14.7        70.925812
381        1  2002             95.0  ...                            0.820       13.3        71.968726
...      ...   ...              ...  ...                              ...        ...              ...
1638       0  2011             59.0  ...                            0.826       14.8        73.446168
1095       1  2010            287.0  ...                            0.405        8.9        65.192254
1130       1  2007            266.0  ...                            0.458        8.4        66.253616
1294       0  2003             72.0  ...                            0.841       15.4        73.096472
860        1  2005             34.0  ...                            0.000        5.4        66.400403

[2350 rows x 21 columns]

In [24]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
model = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(1)])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae'])

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=200,
    batch_size=32)

SyntaxError: invalid non-printable character U+00A0 (1311502501.py, line 2)

In [38]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential([
    Input(shape=(X_train.shape[1],)),

    Dense(256, activation='relu'),
    Dense(128, activation='relu'),

    Dense(1)
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=200,
    batch_size=32,
    callbacks=[early_stop]
)

Epoch 1/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3038.6316 - mae: 52.0391 - val_loss: 682.9492 - val_mae: 22.1330
Epoch 2/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 282.7824 - mae: 13.2413 - val_loss: 130.0108 - val_mae: 9.0344
Epoch 3/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 110.0781 - mae: 8.2057 - val_loss: 96.6775 - val_mae: 7.7604
Epoch 4/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 84.2708 - mae: 7.1980 - val_loss: 79.5623 - val_mae: 6.9665
Epoch 5/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 69.3732 - mae: 6.4958 - val_loss: 68.9956 - val_mae: 6.4792
Epoch 6/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 59.4438 - mae: 5.9954 - val_loss: 59.6653 - val_mae: 6.0015
Epoch 7/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.3433 - mae: 5.5739 - val_loss: 52.9679 - val_mae: 5.6868
Epoch 8/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 44.7404 - mae: 5.2383 - val_loss: 47.2143 - val_mae: 5.3900
Epoch 9/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39.7198 - mae: 4.8932 - val_loss: 42.0038 - val_mae: 5.0798
Epoch 10/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35.6138 - mae: 4.6342 - val_loss: 37.0745 - val_mae: 4.7003
Epoch 11/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31.2100 - mae: 4.3328 - val_loss: 33.7764 - val_mae: 4.4939
Epoch 12/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 27.5516 - mae: 4.0743 - val_loss: 30.6236 - val_mae: 4.2909
Epoch 13/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.0268 - mae: 3.8780 - val_loss: 27.5592 - val_mae: 4.0862
Epoch 14/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.2921 - mae: 3.6429 - val_loss: 25.4692 - val_mae: 3.9153
Epoch 15/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.2688 - mae: 3.4774 - val_loss: 22.8233 - val_mae: 3.7057
Epoch 16/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.5514 - mae: 3.2990 - val_loss: 21.9144 - val_mae: 3.5878
Epoch 17/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16.7440 - mae: 3.1348 - val_loss: 19.1848 - val_mae: 3.3743
Epoch 18/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.1793 - mae: 2.9790 - val_loss: 17.9043 - val_mae: 3.2800
Epoch 19/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13.6947 - mae: 2.8212 - val_loss: 17.5949 - val_mae: 3.2201
Epoch 20/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7626 - mae: 2.7189 - val_loss: 15.3359 - val_mae: 2.9624
Epoch 21/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.5733 - mae: 2.5825 - val_loss: 14.0718 - val_mae: 2.8506
Epoch 22/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.3980 - mae: 2.4289 - val_loss: 12.6479 - val_mae: 2.7151
Epoch 23/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.6931 - mae: 2.3606 - val_loss: 11.7668 - val_mae: 2.5631
Epoch 24/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9239 - mae: 2.2351 - val_loss: 11.2351 - val_mae: 2.5049
Epoch 25/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3466 - mae: 2.1609 - val_loss: 10.2785 - val_mae: 2.3847
Epoch 26/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8866 - mae: 2.1022 - val_loss: 10.3795 - val_mae: 2.3427
Epoch 27/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3054 - mae: 2.0071 - val_loss: 9.0485 - val_mae: 2.1846
Epoch 28/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6511 - mae: 1.9037 - val_loss: 8.1627 - val_mae: 2.1125
Epoch 29/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2378 - mae: 1.8462 - val_loss: 8.0713 - val_mae: 2.1020
Epoch 30/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.8777 - mae: 1.7800 - val_loss: 7.3332 - val_mae: 2.0040
Epoch 31/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.7462 - mae: 1.7408 - val_loss: 7.3104 - val_mae: 2.0244
Epoch 32/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4984 - mae: 1.7813 - val_loss: 10.1536 - val_mae: 2.3454
Epoch 33/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.8944 - mae: 1.7384 - val_loss: 6.9922 - val_mae: 1.9413
Epoch 34/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.8896 - mae: 1.5819 - val_loss: 6.6796 - val_mae: 1.8902
Epoch 35/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.6633 - mae: 1.5457 - val_loss: 6.2687 - val_mae: 1.7663
Epoch 36/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.4717 - mae: 1.5191 - val_loss: 6.4532 - val_mae: 1.8409
Epoch 37/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.3929 - mae: 1.4867 - val_loss: 5.7432 - val_mae: 1.6891
Epoch 38/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.3240 - mae: 1.4715 - val_loss: 5.7724 - val_mae: 1.6990
Epoch 39/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.1935 - mae: 1.4615 - val_loss: 5.6407 - val_mae: 1.6578
Epoch 40/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1499 - mae: 1.4487 - val_loss: 5.9995 - val_mae: 1.7414
Epoch 41/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3247 - mae: 1.4482 - val_loss: 5.5690 - val_mae: 1.7157
Epoch 42/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0291 - mae: 1.3988 - val_loss: 5.4127 - val_mae: 1.6729
Epoch 43/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4.5689 - mae: 1.4858 - val_loss: 5.7481 - val_mae: 1.8282
Epoch 44/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8157 - mae: 1.3790 - val_loss: 5.4496 - val_mae: 1.6239
Epoch 45/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5614 - mae: 1.3209 - val_loss: 5.1811 - val_mae: 1.5772
Epoch 46/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5289 - mae: 1.3404 - val_loss: 5.3225 - val_mae: 1.5759
Epoch 47/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6095 - mae: 1.3327 - val_loss: 5.2158 - val_mae: 1.5914
Epoch 48/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5892 - mae: 1.3061 - val_loss: 5.2366 - val_mae: 1.6917
Epoch 49/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.3252 - mae: 1.2787 - val_loss: 5.2321 - val_mae: 1.5950
Epoch 50/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.3085 - mae: 1.2907 - val_loss: 4.9217 - val_mae: 1.6153
Epoch 51/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.1936 - mae: 1.2601 - val_loss: 4.8301 - val_mae: 1.5415
Epoch 52/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3.0967 - mae: 1.2292 - val_loss: 4.9527 - val_mae: 1.5750
Epoch 53/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0905 - mae: 1.2159 - val_loss: 4.7433 - val_mae: 1.5104
Epoch 54/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.1490 - mae: 1.2370 - val_loss: 4.4291 - val_mae: 1.4362
Epoch 55/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.1573 - mae: 1.2309 - val_loss: 4.6391 - val_mae: 1.4733
Epoch 56/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.5792 - mae: 1.4253 - val_loss: 6.3238 - val_mae: 1.7774
Epoch 57/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.4773 - mae: 1.4010 - val_loss: 4.6634 - val_mae: 1.4773
Epoch 58/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.3747 - mae: 1.2754 - val_loss: 5.8802 - val_mae: 1.6928
Epoch 59/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.1110 - mae: 1.2362 - val_loss: 4.4911 - val_mae: 1.4624
Epoch 60/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0806 - mae: 1.2205 - val_loss: 4.4235 - val_mae: 1.3993
Epoch 61/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8426 - mae: 1.1737 - val_loss: 4.8006 - val_mae: 1.5201
Epoch 62/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7518 - mae: 1.1580 - val_loss: 4.7445 - val_mae: 1.5953
Epoch 63/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6799 - mae: 1.1449 - val_loss: 4.4498 - val_mae: 1.4230
Epoch 64/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 2.6230 - mae: 1.1313 - val_loss: 4.6310 - val_mae: 1.5586
Epoch 65/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6216 - mae: 1.1227 - val_loss: 4.3616 - val_mae: 1.3923
Epoch 66/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6245 - mae: 1.1233 - val_loss: 4.6255 - val_mae: 1.4562
Epoch 67/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6877 - mae: 1.1286 - val_loss: 4.5228 - val_mae: 1.4613
Epoch 68/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7537 - mae: 1.1471 - val_loss: 4.8935 - val_mae: 1.5128
Epoch 69/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8172 - mae: 1.1777 - val_loss: 4.4648 - val_mae: 1.4290
Epoch 70/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6876 - mae: 1.1183 - val_loss: 5.0904 - val_mae: 1.5440
Epoch 71/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0015 - mae: 1.2035 - val_loss: 4.7477 - val_mae: 1.5709
Epoch 72/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5663 - mae: 1.1117 - val_loss: 4.6906 - val_mae: 1.5539
Epoch 73/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8224 - mae: 1.1402 - val_loss: 4.7575 - val_mae: 1.5061
Epoch 74/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.2438 - mae: 1.2873 - val_loss: 4.5920 - val_mae: 1.5857
Epoch 75/200
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.2346 - mae: 1.1821 - val_loss: 5.1329 - val_mae: 1.6013

In [39]:
y_pred = model.predict(X_test)

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

In [40]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 Score:", r2)

MAE: 1.4238361670046438
MSE: 4.4066623672224665
R2 Score: 0.9491354731637567